-- CreateTable
CREATE TABLE "Station" (
    "stationID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "stationName" TEXT NOT NULL DEFAULT 'Keine Daten',
    "city" TEXT,
    "divaNr" INTEGER NOT NULL DEFAULT 99999999999999,
    "longitude" DECIMAL,
    "latitude" DECIMAL
);

-- CreateTable
CREATE TABLE "LineStation" (
    "combinationID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "stationID" INTEGER NOT NULL DEFAULT 99999999999999,
    "lineID" INTEGER NOT NULL DEFAULT 99999999999999,
    "patternID" INTEGER NOT NULL DEFAULT 99999999999999,
    "stopSequenceNumber" INTEGER NOT NULL DEFAULT 99999999999999,
    "direction" INTEGER NOT NULL DEFAULT 99999999999999,
    CONSTRAINT "LineStation_lineID_fkey" FOREIGN KEY ("lineID") REFERENCES "Line" ("lineID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LineStation_stationID_fkey" FOREIGN KEY ("stationID") REFERENCES "Station" ("stationID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Line" (
    "lineID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "lineName" TEXT NOT NULL DEFAULT 'Keine Daten',
    "sortingHelp" INTEGER NOT NULL DEFAULT 99999999999999,
    "realtime" INTEGER NOT NULL DEFAULT 99999999999999,
    "linetype" TEXT NOT NULL DEFAULT 'Keine Daten'
);
